simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUp.as_view(), name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name ='login'),
    path('logout/', auth_views.LogoutView.as_view(),name = 'logout'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace='accounts')), # including the views from accounts
    path('accounts/', include('django.contrib.auth.urls')), # including the django functionalities to handle authorization, we dont even have to register the user model in the admin.py
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

simplesocial/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Simple Social</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-nav align-items-center">
            <a class="navbar-brand mynav" href="{% url 'home' %}">SimpleSocial</a>
            </div>
            <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'posts:all' %}" class="btn btn-simple">Posts</a>
                <a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Create Post</a>
                <a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
                <a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a>
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
            {% endif %}
            </div>
        </div>
    </nav>
          
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="jumbotron">
            <h1>Welcome to SimpleSocial !</h1>
    </div>
    <div class="container">
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates in quis sapiente dolore tenetur error suscipit numquam, deleniti odit. 
            Consequuntur asperiores dolorum fugit magnam doloremque quae suscipit nesciunt ipsa animi.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates in quis sapiente dolore tenetur error suscipit numquam, deleniti odit. 
            Consequuntur asperiores dolorum fugit magnam doloremque quae suscipit nesciunt ipsa animi.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates in quis sapiente dolore tenetur error suscipit numquam, deleniti odit. 
            Consequuntur asperiores dolorum fugit magnam doloremque quae suscipit nesciunt ipsa animi.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates in quis sapiente dolore tenetur error suscipit numquam, deleniti odit. 
            Consequuntur asperiores dolorum fugit magnam doloremque quae suscipit nesciunt ipsa animi.
        </p>
    </div>
    
{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}

{% block content %}
<br>
<h1>You are now logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<br>
<h1> Thanks for visiting, come back soon!</h1>
<h2> You are now logged out.</h2>

{% endblock %}