simplesocial/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path("new/", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<slug>/",views.SingleGroup.as_view(),name="single"),
    path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace='accounts')), # including the views from accounts
    path('accounts/', include('django.contrib.auth.urls')), # including the django functionalities to handle authorization, we dont even have to register the user model in the admin.py
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify # allows to remove chars that arent alphanumeric, swap 'spaces' for dashes (-), lowercase strings, set up that string basically so it can be used as a url
import misaka # allows link embedding, markdown text, misaka needs to be pip installed (requires VS C++ v14, and Win10 SDK)
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library() # this allows to use later get_ to fetch user_groups from GroupMember

# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    slug = models.SlugField(allow_unicode=True, unique = True)
    description = models.TextField(blank=True,default= '')
    description_html = models.TextField(editable=False, default='',blank=True )
    members = models.ManyToManyField(User, through= 'GroupMember')

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug} )

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name = 'memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name = 'user_groups', on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group', 'user')

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin  
from django.urls import reverse
from django.views.generic import DetailView, TemplateView, CreateView, ListView, RedirectView
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import Group, GroupMember
from . import models    

# Create your views here.
class CreateGroup(LoginRequiredMixin, CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(DetailView):
    model = Group

class ListGroups(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %} {% endblock %} <!--#different blocks in case we want to add something before or after the actual group_content-->
        {% block group_content %} {% endblock %}
        {% block postgroup %} {% endblock %}
    </div>
</div>

{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %} 
<div class="container col-md-4">
<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>

    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
                <span class="glyphicon glyphicon-remove-circle"></span>Leave Group
            </a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
                <span class="glyphicon glyphicon-ok-circle"></span>Join Group
            </a>
        {% endif %}
    </div>
</div>

{% endblock %} 

{% block group_content %} 
<div class="col-md-8">
    <div class="list-group">
        {% if group.posts.count == 0 %}
            <h2>No posts in this Group yet </h2>
        {% else %}
            {% for post in group.posts.all %}
                <div class="list-group-item list-group-item-action list-group-item-light">
                {% include 'posts/_post.html' %}
                </div>
            {% endfor%}
        {% endif %}

    </div>
</div>

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% load bootstrap4 %}

{% block group_content %}
    <h4>Create New Group</h4>
    <div class="container">
    <form action="{% url 'groups:create' %}" method="post" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary btn-lg">
    </form>
    </div>

{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome Back!
                    <a href="{% url 'posts:for_user' username=user.username %}" >@{{user.username}}</a>
                </h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the Groups page</p>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-lg btn-fill btn-warning">
                <span class="glyphicon glyphicon-plus-sign"></span>Create A New Group
            </a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item list-group-item-action list-group-item-light">
                    <h3 class="title list-group-item-heading" style="color:#007bff;">{{group.name}}</h3>
                    <div class="list-group-item-text container-fluid">
                        {{group.description_html|safe}} <!--#safe will display any bold or italic text (etc) correctly instead of the html tags-->
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge badge-primary badge-pill">{{group.members.count}}</span>
                                member{{group.members.count|pluralize}}
                            </div>
                            <div class="col-md-4">
                                <span class="badge badge-primary badge-pill">{{group.posts.count}}</span>
                                post{{group.posts.count|pluralize}}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{%endblock%}